Feature 770 Storage Group Snapshots
dell/gopowermax pull request #47
Opened 2023-04-25 14:52 UTC by doriac11

# Description
- Add CRUD Operations for Storage Group Snapshots.

# GitHub Issues
List the GitHub issues impacted by this PR:
| GitHub Issue # |
| https://github.com/dell/csm/issues/770 |

# Checklist:

- [x] Have you run format,vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [x] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [x] Have you done corresponding changes to the documentation
- [ ] Did you run tests in a real Kubernetes cluster?
- [x] Have you maintained at least 90% code coverage?
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Ran new Integration tests against a PowerMax System

2023-04-27 06:48 UTC, shanmydell requested changes
Please fix the linting errors

2023-04-27 08:03 UTC, tssushma commented
I am seeing few errors when running the gopowermax test with this branch. Could you please check it once.
And also Go formatting has failed.

+ golint -set_exit_status ./...
interface.go:140:91: interface method parameter snapshotId should be snapshotID
interface.go:143:88: interface method parameter snapshotId should be snapshotID
interface.go:143:100: interface method parameter snapId should be snapID
interface.go:149:87: interface method parameter snapshotId should be snapshotID
interface.go:149:106: interface method parameter snapId should be snapID
interface.go:152:87: interface method parameter snapshotId should be snapshotID
interface.go:152:106: interface method parameter snapId should be snapID
replication.go:31:2: const SnapId should be SnapID
replication.go:34:6: exported type SnapshotAction should have comment or be unexported
replication.go:49:1: comment on exported method Client.GetStorageGroupSnapshots should be of the form "GetStorageGroupSnapshots ..."
replication.go:90:1: comment on exported method Client.GetStorageGroupSnapshotSnapIds should be of the form "GetStorageGroupSnapshotSnapIds ..."
replication.go:93:107: method parameter snapshotId should be snapshotID
replication.go:123:1: comment on exported method Client.GetStorageGroupSnapshotSnap should be of the form "GetStorageGroupSnapshotSnap ..."
replication.go:126:104: method parameter snapshotId should be snapshotID
replication.go:126:116: method parameter snapId should be snapID
replication.go:156:1: comment on exported method Client.CreateStorageGroupSnapshot should be of the form "CreateStorageGroupSnapshot ..."
replication.go:175:1: comment on exported method Client.ModifyStorageGroupSnapshot should be of the form "ModifyStorageGroupSnapshot ..."
replication.go:178:103: method parameter snapshotId should be snapshotID
replication.go:178:122: method parameter snapId should be snapID
replication.go:254:1: comment on exported method Client.DeleteStorageGroupSnapshot should be of the form "DeleteStorageGroupSnapshot ..."
replication.go:257:103: method parameter snapshotId should be snapshotID
replication.go:257:122: method parameter snapId should be snapID
inttest/pmax_replication_integration_test.go:145:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:193:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:201:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:218:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:235:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:252:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:269:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:278:9: if block ends with a return statement, so drop this else and outdent its block
types/v100/snapshot.go:192:2: struct field SnapId should be SnapID
types/v100/snapshot.go:223:1: comment on exported type SourceVolume should be of the form "SourceVolume ..." (with optional leading article)
types/v100/snapshot.go:256:6: exported type RenameStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:262:6: exported type RestoreStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:268:6: exported type LinkStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:274:6: exported type RelinkStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:280:6: exported type UnlinkStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:286:6: exported type SetModeStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:292:6: exported type TimeToLiveStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:298:6: exported type SecureStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:304:6: exported type PersistStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:385:1: comment on exported type SnapId should be of the form "SnapId ..." (with optional leading article)
types/v100/snapshot.go:386:6: type SnapId should be SnapID
Found 43 lint suggestions; failing.

2023-04-27 13:10 UTC, doriac11 commented
Hello @tssushma and @shanmydell ,

Thanks for the comments, this is my first time adding to this repo.

I have fixed the test and linting errors

# Test
```
go test -timeout 30s -run ^TestCrudStorageGroupSnapshot github.com/dell/gopowermax/v2/inttest
ok      github.com/dell/gopowermax/v2/inttest   19.584s
```

# Linting
```
$ make check
gofmt -w authenticate.go interface.go system.go sloprovisioning.go VolumeSnapshot.go VolumeReplication.go metrics.go ArrayMigration.go unit_test.go unit_steps_test.go inttest/pmax_integration_test.go inttest/pmax_replication_integration_test.go
golint -set_exit_status
go vet
```

2023-04-28 11:48 UTC, tssushma commented
> Hello @tssushma and @shanmydell ,
> 
> Thanks for the comments, this is my first time adding to this repo.
> 
> I have fixed the test and linting errors
> 
> # Test
> ```
> go test -timeout 30s -run ^TestCrudStorageGroupSnapshot github.com/dell/gopowermax/v2/inttest
> ok      github.com/dell/gopowermax/v2/inttest   19.584s
> ```
> 
> # Linting
> ```
> $ make check
> gofmt -w authenticate.go interface.go system.go sloprovisioning.go VolumeSnapshot.go VolumeReplication.go metrics.go ArrayMigration.go unit_test.go unit_steps_test.go inttest/pmax_integration_test.go inttest/pmax_replication_integration_test.go
> golint -set_exit_status
> go vet
> ```

@doriac11 I re-checked it and I am still seeing the errors. Could you please check it one more time.

inttest/pmax_replication_integration_test.go:117:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:125:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:142:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:159:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:176:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:193:9: if block ends with a return statement, so drop this else and outdent its block
inttest/pmax_replication_integration_test.go:202:9: if block ends with a return statement, so drop this else and outdent its block
types/v100/snapshot.go:223:1: comment on exported type SourceVolume should be of the form "SourceVolume ..." (with optional leading article)
types/v100/snapshot.go:256:6: exported type RenameStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:262:6: exported type RestoreStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:268:6: exported type LinkStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:274:6: exported type RelinkStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:280:6: exported type UnlinkStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:286:6: exported type SetModeStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:292:6: exported type TimeToLiveStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:298:6: exported type SecureStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:304:6: exported type PersistStorageGroupSnapshot should have comment or be unexported
types/v100/snapshot.go:385:1: comment on exported type SnapID should be of the form "SnapID ..." (with optional leading article)
Found 18 lint suggestions; failing.

2023-04-28 13:31 UTC, doriac11 commented
@tssushma I think I fixed now,

It was kind of weird, those errors weren't showing up when I did the `make check` but when I ran the `golint` on the files directly then the link errors showed up.

2023-05-04 11:02 UTC, shanmydell requested changes

2023-05-04 11:02 UTC, shanmydell commented on replication.go
> + Copyright © 2020 Dell Inc. or its subsidiaries. All Rights Reserved.
change to 2023

2023-05-04 11:41 UTC, doriac11 commented on replication.go
> + Copyright © 2020 Dell Inc. or its subsidiaries. All Rights Reserved.
Updated!

2023-05-08 09:44 UTC, tssushma approved these changes
lgtm
Tests are passed.

2023-05-08 12:27 UTC, doriac11 commented
@shanmydell I have made updates for the Lint, Unit and Integration tests, could you please review again now?

Thanks!

2023-05-08 12:36 UTC, shanmydell approved these changes

2023-05-08 12:37 UTC, merged